server:
  port: 8080
spring:
  application:
    name: transfer-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus_db
    username: otus
    password: otus
  jpa:
    show-sql: true
    open-in-view: false
