server:
  port: 8080
spring:
  application:
    name: mt-core-transfers
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mt_core_transfers
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: 127.0.0.1:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: "TransferStatus:ru.otus.java.pro.mt.core.transfers.dtos.KafkaTransferStatusDto"

transfers:
  max-transfer-sum: 100.00
  demo-transfers-enabled: false
  blocked-account-numbers:
    - "123"
    - "234"
    - "456"
integrations:
  limits:
    rest-client:
      url: http://localhost:8080/api/v1/limits
      read-timeout: 30s
      connect-timeout: 60s
logging:
  level:
    org.zalando.logbook.Logbook: TRACE